config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'about' => 'static_pages#about'

  resources :organizations, path: "", only: [:show] do
    resources :people, as: 'users', controller: 'users',
      only: [:create, :show, :edit, :update, :index]

    resources :groups, only: [:create, :show, :index, :destroy] do
      # New conversations
      resources :messages, only: [:create]
      resources :roles, only: [:new, :create]
    end

    resources :conversations, only: [:show, :update] do
      # New messages in an existing converation
      resources :messages, only: [:create]
    end

    # resources :messages, only: [:update]
    resources :roles, only: [:show, :edit, :update, :destroy]
  end

  root 'static_pages#home'
end

app/views/shared/_group_secondary.html.erb
<hr class="grp-hr">
<h1 class="app-sectionHeader">
  Roles in <%= link_to group.name, [group.organization, group],
      class: "app-headingLink" %>
</h1>
<table class="rol-list-table">
  <% group.roles.each do |role| %>
    <tr>
      <td class="rol-list-td">
        <%= link_to role.name, [group.organization, role] %>
      </td>
      <td>
        <% if role.role_assignments.empty? %>
          -
        <% else %>
          <% role.role_assignments.ordered_by_user.each do |assignment| %>
            <div>
              <%= link_to assignment.user.name,
                [group.organization, assignment.user],
                class: "app-subtleLink"%>
            </div>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  <tr>
    <td role="action-link"><%= link_to "New..",
      new_organization_group_role_path(group.organization, group) %></td>
  </tr>
</table>

app/views/shared/_navbar_side.html.erb
<hr class="nbs-hr">
<nav class="nbs">
  <div class="nbs-leftDiv">
    <section class="nbs-groups nbs-section" id="groups:list" data-turbolinks-temporary>
      <h1 class="app-sectionHeader">
        <%= link_to "Groups", organization_groups_path(org),
          class: "app-headingLink" %>
      </h1>
      <ul class="nbs-grpList">
        <% org.groups.all.each do |group| %>
          <% count = group.conversations.unread_by(current_user).count %>
          <li><%= link_to group.name,
            [org, group] %><%= " (#{count})" if count > 0 %></li>
        <% end %>
        <li><%= link_to "New...", organization_groups_path(org) %></li>
      </ul>
    </section>
  </div>

  <div class="nbs-rightDiv">
    <section class="nbs-people nbs-section">
      <h1 class="app-sectionHeader">
        <%= link_to "People", organization_users_path(org),
          class: "app-headingLink" %>
      </h1>
    </section>

    <section class="nbs-me nbs-section">
      <h1 class="app-sectionHeader">
        <%= link_to "Me", [org, current_user],
          class: "app-headingLink" %>
      </h1>
    </section>
  </div>

  <section class="nbs-session">
    <%= log_in_out_link_bottom %>
  </section>
</nav>

app/views/shared/_navbar_top.html.erb
<nav class="nav-top">
  <div class="nav-topLeft">
    <%= link_to org do %>
      <%= image_tag "genus-logo-t.png", alt: "Genus",
               class: "nav-logo-top" %><%= org.name %>
    <% end %>
  </div>
  <div class="nav-topRight">
    <a href="#app-aside" class="nav-menuLink">Jump to Menu</a>
    <%= log_in_out_link_top %>
  </div>
</nav>